### ISSUE TITLE
Re-factor the initEncryptionSchema method

### ISSUE THREAD

**Issue by mquandalle** [Planifica/encryption#7]
Currently the server-side code define the following method:

``` js
initEncryptionSchema: function (collectionName, fieldKey) {
    var schema = {};
    schema[fieldKey] = {
        type: Boolean,
        defaultValue: false
    };
    // add ecrypted field to the collection schema
    Mongo.Collection.get(collectionName).attachSchema(schema);
}
```

This method allow an attacker to break any application using this package by overwriting some fields definitions on the server-side schema.

**Comment by mquandalle** [comment]
BTW, being able to overwrite a field definition is a design decision of SimpleSchema, cf. https://github.com/aldeed/meteor-simple-schema/blob/302388c2f2418267a8ef5be767b5d0595875ccb2/simple-schema.js#L229-L231

**Comment by PhilippSpo** [comment]
You are right. I added this last evening without thinking about it too much.

**Comment by PhilippSpo** [comment]
Alright the method now prevents already defined fields from being overwritten.

**Comment by mquandalle** [comment]
I'm still not comfortable with any user being able to modify the schema of my server-side collections. An attack could be to create a lot of fields on the server (that would be auto-filled using the simple-schema `defaultValue`) which will certainly break the app in a lot of different places.

I strongly think that this shouldn't use a Meteor method but use a classical function call on the server.

**Comment by PhilippSpo** [comment]
In order to achieve that we need to add some server-side logic to EncryptionCollection.

**Comment by PhilippSpo** [comment]
I created a branch for this issue: https://github.com/Planifica/encryption/tree/server-side-collection-encryption
what do you think of this?
