### ISSUE TITLE
Support public (unencrypted) documents

### ISSUE THREAD

**Issue by mquandalle** [Planifica/encryption#8]
Hi Philipp,

I'm considering using this package in a hosted (“SASS”) version of http://wekan.io to encrypt user data (boards, cards, files). One particular need that I have is to support public boards that can be read by anyone. Do you have any suggestion about how this could be implemented using the `planifica:encryption` package? Maybe this would require adding a `encryptionCondition(doc) -> bool` option for the `CollectionEncryption` constructor?

**Comment by PhilippSpo** [comment]
Glad to hear you consider using it in wekan :)
Yes a `encryptionCondition` definitely makes sense. Do you want to go for a PR?
